### ISSUE TITLE
rebel(row|col_merged = ) を rebel(row_header = 1:5, col_header = 1:3) のように変更する

### ISSUE THREAD

**Issue by kikirinrin** [kikirinrin/lucifer#130]
また `pos` っちゃった

**Comment by kikirinrin** [comment]
#88 の議論を活かしたいが，ここでは `along` というニュアンスは適さない．

**Comment by kikirinrin** [comment]
これと戦う単機能関数は，`unmerge_vert()` だが
https://github.com/kikirinrin/lucifer/blob/d0e36fcc51153bbbd4b0308072e816c03c544a9d/R/shapetools.R#L59-L66

**Comment by kikirinrin** [comment]
少なくとも，複数行|列に対応させないといけない

**Comment by akimanabe** [comment]
これは `dir` と `pos` 不可避案件

**Comment by kikirinrin** [comment]
うーむ

**Comment by kikirinrin** [comment]
cluster の検索列を最左にすると情報が損失することがああｋ

**Comment by kikirinrin** [comment]
解決の方向性が見えたつもりでいたが，やはりだめ．
上の例では，鉛直方向のセル結合が目立つが，水平方向にもセル結合されている．
実際にコーディングしていて混乱した．

- `unmerge_header = list(header_of = "row", pos = 1:5)` <- これは結合がおきているのが1:5列目であると言っている．
pos は '行' を指定しているわけではない．
なぜなら，行ヘッダだから．行1~5は結合されているけど，6~30は結合されてないっす，なんてことは起きない．

**Comment by kikirinrin** [comment]
書いていて思ったのが，結合の有無にかかわらず，複数行|列ヘッダの範囲をしていするようにしたらどうだろう．
うえの農林統計の例だと
- `row_header = 1:5`
- `col_header = 1:3`　（画像にはないが）

セル結合の有無にかかわらず，複数次元ヘッダを毎回整形するようにすれば，
- きれいなデータには何も起きない（同じもので上書きされる）
- 汚いデータを少ない引数で整形できる
メリットを享受できる

**Comment by kikirinrin** [comment]
長くなったので別Issueへ
