### ISSUE TITLE
えひめ H30漁業種類�別月別水揚量.xls@マサバとゴマｻﾊﾞ集計 をrebel()で読んだ時のNA行の挿入について

### ISSUE THREAD

**Issue by JK-junkin** [kikirinrin/lucifer#135]
15愛媛でhard code作業中、**えひめ H30漁業種類�別月別水揚量.xls**の**マサバとゴマｻﾊﾞ集計**シートを読んだ際にNA行が混入した。下記に読み込み時の設定（完全な整形までは行なっていない）と出力結果を示す。

```r
res <- rebel(path = ./15愛媛/えひめ H30漁業種類�別月別水揚量.xls,
             sheet_regex = ".*\\p{Katakana}+.*",
             cluster = list(
               dir = "h",
               pos = 2,
               regex = "^年",
               offset = c(0, 0),
               ends = list(row = "2019年", col = "^マサバ.*"),
               info = list(offset = c(-1, 0), dim = c(1, 1))
             )) #,
```
<img width="816" alt="ehime_NArows" src="https://user-images.githubusercontent.com/50478487/60802191-5774c880-a1b3-11e9-873b-02b5375afe60.png">

**Comment by kikirinrin** [comment]
クラスタによって info の offset がゆらぐ事象を確認

**Comment by kikirinrin** [comment]
NA行混入については，ends 周りのバグかな？

**Comment by kikirinrin** [comment]
https://github.com/kikirinrin/lucifer/blob/d0e36fcc51153bbbd4b0308072e816c03c544a9d/R/shapetools.R#L264
