### ISSUE TITLE
tbl2rebelが見つからない？

### ISSUE THREAD

**Issue by akimanabe** [kikirinrin/lucifer#167]
luciferをdevからインストールしました。
tbl2rebelのmanualはあるけどFunctionは実装されてない？

あるいはmasterにはあるのでしょうか。一応質問立てておきます。すみません。

![tbl2rebel](https://user-images.githubusercontent.com/50477364/61338305-b30a1a80-a873-11e9-99f3-5f71766f9bcc.png)

**Comment by kikirinrin** [comment]
単純なエクスポート忘れでした．失礼しました．
