### ISSUE TITLE
extract_clusters()の引数名, row? pos?

### ISSUE THREAD

**Issue by kikirinrin** [kikirinrin/lucifer#88]
`(dir = "row", pos = 1)` ではなく
`(serch_along = "col = 1")` とする

**Comment by akimanabe** [comment]
良いと思います。 `pos` よりずっと分かりやすいです。
 `tidyverse` 的な命名法だと
`search_row = 1` とか `search_col = 1` とか・・・？でも 'along' って言葉はシンプルかつ強い説明力を持っているのでこれで `search_along` でよさそうですね 😃

**Comment by kikirinrin** [comment]
じゃ
- `search_along_row = 2`
- `search_along_col = 3` 

ですかね？

**Comment by akimanabe** [comment]
それでいいと思います 👍

**Comment by JK-junkin** [comment]
search_along_、いいですね。search_along_row <=> dir = “horiz” と考えていいですか？

**Comment by kikirinrin** [comment]
> search_along_、いいですね。search_along_row <=> dir = “horiz” と考えていいですか？

そうです！
